create type rating_type as enum ('1', '2', '3', '4', '5');

create table bookmarks (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text not null,
  "url" text not null,
  "desc" text ,
  rating rating_type not null
)